{% set name = "requests" %}
{% set version = "2.25.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 27973dd4a904a4f13b263a19c866c13b92a39ed1c964655f025f3f8d3d75b804

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - certifi >=2017.4.17
    - chardet >=3.0.2,<5
    - idna >=2.5,<3
    - pip
    - python
    - urllib3 >=1.21.1,<1.27
  run:
    - certifi >=2017.4.17
    - chardet >=3.0.2,<5
    - idna >=2.5,<3
    - python
    - urllib3 >=1.21.1,<1.27

test:
  imports:
    - requests
  requires:
    - pysocks >=1.5.6,!=1.5.7
    - pytest >=3
    - pytest-cov
    - pytest-httpbin ==0.0.7
    - pytest-mock
    - pytest-xdist

about:
  home: "https://requests.readthedocs.io"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "Python HTTP for Humans."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
