{% set name = "certifi" %}
{% set version = "2020.12.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1a4995114262bffbc2413b159f2a1a480c969de6e6eb13ee966d470af86af59c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: "https://certifiio.readthedocs.io/en/latest/"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file: 
  summary: "Python package for providing Mozilla's CA Bundle."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
