{% set name = "humbug" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 44ae7e7acbc68a56aa3b1b7632cf39e016940bc6efa3afca6dad94f6c919e2ae

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - requests
  run:
    - python
    - requests

test:
  imports:
    - humbug

about:
  home: "https://github.com/bugout-dev/humbug"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "Humbug: Do you build developer tools? Humbug helps you know your users."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
